workflows:
  my-workflow:
    name: Codemagic Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Initialize keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$(xcode-project detect-bundle-id)" --type IOS_APP_STORE --create
      - name: Set up signing certificate
        script: |
          keychain add-certificates
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      - name: Get dependencies
        script: |
          flutter packages pub get
      - name: Build Android App
        script: |
          flutter build apk --release
      - name: Build iOS App
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - "*.log"
    publishing:
      email:
        recipients:
          - user@example.com
      app_store_connect:
        auth: integration

